// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tranzor.Context;


#nullable disable

namespace Tranzor.Migrations
{
    [DbContext(typeof(GtfsDbContext))]
    [Migration("20250704153504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tranzor.Models.Agency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AgencyEmail")
                        .HasColumnType("text")
                        .HasColumnName("agency_email");

                    b.Property<string>("AgencyFareUrl")
                        .HasColumnType("text")
                        .HasColumnName("agency_fare_url");

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_id");

                    b.Property<string>("AgencyLang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_lang");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_name");

                    b.Property<string>("AgencyPhone")
                        .HasColumnType("text")
                        .HasColumnName("agency_phone");

                    b.Property<string>("AgencyTimezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_timezone");

                    b.Property<string>("AgencyUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_url");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_agencies_agency_id");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Calendar", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_date");

                    b.Property<int>("Friday")
                        .HasColumnType("integer")
                        .HasColumnName("friday");

                    b.Property<int>("Monday")
                        .HasColumnType("integer")
                        .HasColumnName("monday");

                    b.Property<int>("Saturday")
                        .HasColumnType("integer")
                        .HasColumnName("saturday");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_date");

                    b.Property<int>("Sunday")
                        .HasColumnType("integer")
                        .HasColumnName("sunday");

                    b.Property<int>("Thursday")
                        .HasColumnType("integer")
                        .HasColumnName("thursday");

                    b.Property<int>("Tuesday")
                        .HasColumnType("integer")
                        .HasColumnName("tuesday");

                    b.Property<int>("Wednesday")
                        .HasColumnType("integer")
                        .HasColumnName("wednesday");

                    b.HasKey("Id")
                        .HasName("pk_calendars");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_calendars_service_id");

                    b.ToTable("calendars", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.CalendarDate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer")
                        .HasColumnName("exception_type");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_calendar_dates");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_calendar_dates_service_id");

                    b.ToTable("calendar_dates", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.FareAttribute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_type");

                    b.Property<string>("FareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fare_id");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int?>("TransferDuration")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_duration");

                    b.Property<int>("Transfers")
                        .HasColumnType("integer")
                        .HasColumnName("transfers");

                    b.HasKey("Id")
                        .HasName("pk_fare_attributes");

                    b.HasIndex("FareId")
                        .HasDatabaseName("ix_fare_attributes_fare_id");

                    b.ToTable("fare_attributes", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.FareRule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ContainsId")
                        .HasColumnType("text")
                        .HasColumnName("contains_id");

                    b.Property<string>("DestinationId")
                        .HasColumnType("text")
                        .HasColumnName("destination_id");

                    b.Property<string>("FareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fare_id");

                    b.Property<string>("OriginId")
                        .HasColumnType("text")
                        .HasColumnName("origin_id");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.HasKey("Id")
                        .HasName("pk_fare_rules");

                    b.HasIndex("FareId")
                        .HasDatabaseName("ix_fare_rules_fare_id");

                    b.ToTable("fare_rules", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Route", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AgencyId")
                        .HasColumnType("text")
                        .HasColumnName("agency_id");

                    b.Property<int?>("ContinuousDropOff")
                        .HasColumnType("integer")
                        .HasColumnName("continuous_drop_off");

                    b.Property<int?>("ContinuousPickup")
                        .HasColumnType("integer")
                        .HasColumnName("continuous_pickup");

                    b.Property<string>("RouteColor")
                        .HasColumnType("text")
                        .HasColumnName("route_color");

                    b.Property<string>("RouteDesc")
                        .HasColumnType("text")
                        .HasColumnName("route_desc");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteLongName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_long_name");

                    b.Property<string>("RouteShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_short_name");

                    b.Property<int?>("RouteSortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("route_sort_order");

                    b.Property<string>("RouteTextColor")
                        .HasColumnType("text")
                        .HasColumnName("route_text_color");

                    b.Property<int>("RouteType")
                        .HasColumnType("integer")
                        .HasColumnName("route_type");

                    b.Property<string>("RouteUrl")
                        .HasColumnType("text")
                        .HasColumnName("route_url");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_routes_route_id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Shape", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<double?>("ShapeDistTraveled")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_dist_traveled");

                    b.Property<string>("ShapeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shape_id");

                    b.Property<double>("ShapePtLat")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_pt_lat");

                    b.Property<double>("ShapePtLon")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_pt_lon");

                    b.Property<int>("ShapePtSequence")
                        .HasColumnType("integer")
                        .HasColumnName("shape_pt_sequence");

                    b.HasKey("Id")
                        .HasName("pk_shapes");

                    b.HasIndex("ShapeId")
                        .HasDatabaseName("ix_shapes_shape_id");

                    b.ToTable("shapes", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Stop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("location_type");

                    b.Property<string>("ParentStation")
                        .HasColumnType("text")
                        .HasColumnName("parent_station");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("text")
                        .HasColumnName("platform_code");

                    b.Property<string>("StopCode")
                        .HasColumnType("text")
                        .HasColumnName("stop_code");

                    b.Property<string>("StopDesc")
                        .HasColumnType("text")
                        .HasColumnName("stop_desc");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<double>("StopLat")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_lat");

                    b.Property<double>("StopLon")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_lon");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_name");

                    b.Property<string>("StopTimezone")
                        .HasColumnType("text")
                        .HasColumnName("stop_timezone");

                    b.Property<string>("StopUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_url");

                    b.Property<int?>("WheelchairBoarding")
                        .HasColumnType("integer")
                        .HasColumnName("wheelchair_boarding");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_stops");

                    b.HasIndex("StopId")
                        .HasDatabaseName("ix_stops_stop_id");

                    b.ToTable("stops", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.StopTime", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrival_time");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departure_time");

                    b.Property<int?>("DropOffType")
                        .HasColumnType("integer")
                        .HasColumnName("drop_off_type");

                    b.Property<int?>("PickupType")
                        .HasColumnType("integer")
                        .HasColumnName("pickup_type");

                    b.Property<double?>("ShapeDistTraveled")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_dist_traveled");

                    b.Property<string>("StopHeadsign")
                        .HasColumnType("text")
                        .HasColumnName("stop_headsign");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("stop_sequence");

                    b.Property<int?>("Timepoint")
                        .HasColumnType("integer")
                        .HasColumnName("timepoint");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_stop_times");

                    b.HasIndex("StopId")
                        .HasDatabaseName("ix_stop_times_stop_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_stop_times_trip_id");

                    b.ToTable("stop_times", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Transfer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("FromStopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_stop_id");

                    b.Property<int?>("MinTransferTime")
                        .HasColumnType("integer")
                        .HasColumnName("min_transfer_time");

                    b.Property<string>("ToStopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_stop_id");

                    b.Property<int>("TransferType")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_type");

                    b.HasKey("Id")
                        .HasName("pk_transfers");

                    b.HasIndex("FromStopId")
                        .HasDatabaseName("ix_transfers_from_stop_id");

                    b.HasIndex("ToStopId")
                        .HasDatabaseName("ix_transfers_to_stop_id");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("BikesAllowed")
                        .HasColumnType("integer")
                        .HasColumnName("bikes_allowed");

                    b.Property<string>("BlockId")
                        .HasColumnType("text")
                        .HasColumnName("block_id");

                    b.Property<int?>("DirectionId")
                        .HasColumnType("integer")
                        .HasColumnName("direction_id");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("ShapeId")
                        .HasColumnType("text")
                        .HasColumnName("shape_id");

                    b.Property<string>("TripHeadsign")
                        .HasColumnType("text")
                        .HasColumnName("trip_headsign");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<string>("TripShortName")
                        .HasColumnType("text")
                        .HasColumnName("trip_short_name");

                    b.Property<int?>("WheelchairAccessible")
                        .HasColumnType("integer")
                        .HasColumnName("wheelchair_accessible");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_trips_route_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_trips_service_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trips_trip_id");

                    b.ToTable("trips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
