// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tranzor.Context;

#nullable disable

namespace Tranzor.Migrations
{
    [DbContext(typeof(GtfsDbContext))]
    [Migration("20250808210119_CreateStopCity")]
    partial class CreateStopCity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tranzor.Models.Agency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AgencyEmail")
                        .HasColumnType("text")
                        .HasColumnName("agency_email");

                    b.Property<string>("AgencyFareUrl")
                        .HasColumnType("text")
                        .HasColumnName("agency_fare_url");

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_id");

                    b.Property<string>("AgencyLang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_lang");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_name");

                    b.Property<string>("AgencyPhone")
                        .HasColumnType("text")
                        .HasColumnName("agency_phone");

                    b.Property<string>("AgencyTimezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_timezone");

                    b.Property<string>("AgencyUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_url");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_agencies");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_gtfs_agencies_agency_id");

                    b.ToTable("gtfs_agencies", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.AgencyTranslation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("RecordSubId")
                        .HasColumnType("text")
                        .HasColumnName("record_sub_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<string>("TranslationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translation_text");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_translations");

                    b.HasIndex("TableName")
                        .HasDatabaseName("ix_gtfs_translations_table_name");

                    b.ToTable("gtfs_translations", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Attribution", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AgencyId")
                        .HasColumnType("text")
                        .HasColumnName("agency_id");

                    b.Property<string>("AttributionEmail")
                        .HasColumnType("text")
                        .HasColumnName("attribution_email");

                    b.Property<string>("AttributionPhone")
                        .HasColumnType("text")
                        .HasColumnName("attribution_phone");

                    b.Property<string>("AttributionUrl")
                        .HasColumnType("text")
                        .HasColumnName("attribution_url");

                    b.Property<bool>("IsAuthority")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authority");

                    b.Property<bool>("IsOperator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_operator");

                    b.Property<bool>("IsProducer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_producer");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_name");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_attributions");

                    b.HasIndex("OrganizationName")
                        .HasDatabaseName("ix_gtfs_attributions_organization_name");

                    b.ToTable("gtfs_attributions", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Calendar", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_date");

                    b.Property<int>("Friday")
                        .HasColumnType("integer")
                        .HasColumnName("friday");

                    b.Property<int>("Monday")
                        .HasColumnType("integer")
                        .HasColumnName("monday");

                    b.Property<int>("Saturday")
                        .HasColumnType("integer")
                        .HasColumnName("saturday");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_date");

                    b.Property<int>("Sunday")
                        .HasColumnType("integer")
                        .HasColumnName("sunday");

                    b.Property<int>("Thursday")
                        .HasColumnType("integer")
                        .HasColumnName("thursday");

                    b.Property<int>("Tuesday")
                        .HasColumnType("integer")
                        .HasColumnName("tuesday");

                    b.Property<int>("Wednesday")
                        .HasColumnType("integer")
                        .HasColumnName("wednesday");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_calendars");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_gtfs_calendars_service_id");

                    b.ToTable("gtfs_calendars", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.CalendarDate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer")
                        .HasColumnName("exception_type");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_calendar_dates");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_gtfs_calendar_dates_service_id");

                    b.ToTable("gtfs_calendar_dates", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.FareAttribute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_type");

                    b.Property<string>("FareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fare_id");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int?>("TransferDuration")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_duration");

                    b.Property<int>("Transfers")
                        .HasColumnType("integer")
                        .HasColumnName("transfers");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_fare_attributes");

                    b.HasIndex("FareId")
                        .HasDatabaseName("ix_gtfs_fare_attributes_fare_id");

                    b.ToTable("gtfs_fare_attributes", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.FareLegRule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("FareLegRuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fare_leg_rule_id");

                    b.Property<string>("FareProductId")
                        .HasColumnType("text")
                        .HasColumnName("fare_product_id");

                    b.Property<string>("LegGroupId")
                        .HasColumnType("text")
                        .HasColumnName("leg_group_id");

                    b.Property<string>("NetworkId")
                        .HasColumnType("text")
                        .HasColumnName("network_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_fare_leg_rules");

                    b.HasIndex("FareLegRuleId")
                        .HasDatabaseName("ix_gtfs_fare_leg_rules_fare_leg_rule_id");

                    b.ToTable("gtfs_fare_leg_rules", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.FareMedia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FareMediaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fare_media_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_fare_media");

                    b.HasIndex("FareMediaId")
                        .HasDatabaseName("ix_gtfs_fare_media_fare_media_id");

                    b.ToTable("gtfs_fare_media", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.FareProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FareProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fare_product_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_fare_products");

                    b.HasIndex("FareProductId")
                        .HasDatabaseName("ix_gtfs_fare_products_fare_product_id");

                    b.ToTable("gtfs_fare_products", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.FareRule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ContainsId")
                        .HasColumnType("text")
                        .HasColumnName("contains_id");

                    b.Property<string>("DestinationId")
                        .HasColumnType("text")
                        .HasColumnName("destination_id");

                    b.Property<string>("FareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fare_id");

                    b.Property<string>("OriginId")
                        .HasColumnType("text")
                        .HasColumnName("origin_id");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_fare_rules");

                    b.HasIndex("FareId")
                        .HasDatabaseName("ix_gtfs_fare_rules_fare_id");

                    b.ToTable("gtfs_fare_rules", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.FeedInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("FeedContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("feed_contact_email");

                    b.Property<string>("FeedContactUrl")
                        .HasColumnType("text")
                        .HasColumnName("feed_contact_url");

                    b.Property<string>("FeedEndDate")
                        .HasColumnType("text")
                        .HasColumnName("feed_end_date");

                    b.Property<string>("FeedLang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feed_lang");

                    b.Property<string>("FeedPublisherName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feed_publisher_name");

                    b.Property<string>("FeedPublisherUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feed_publisher_url");

                    b.Property<string>("FeedStartDate")
                        .HasColumnType("text")
                        .HasColumnName("feed_start_date");

                    b.Property<string>("FeedVersion")
                        .HasColumnType("text")
                        .HasColumnName("feed_version");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_feed_info");

                    b.HasIndex("FeedPublisherName")
                        .HasDatabaseName("ix_gtfs_feed_info_feed_publisher_name");

                    b.ToTable("gtfs_feed_info", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Gtfs.External.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<short?>("AdminLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("admin_level");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<MultiPolygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_cities_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Gtfs.External.StopCity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city_id");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.HasKey("Id")
                        .HasName("pk_stop_cities");

                    b.ToTable("stop_cities", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Network", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("network_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_networks");

                    b.HasIndex("NetworkId")
                        .HasDatabaseName("ix_gtfs_networks_network_id");

                    b.ToTable("gtfs_networks", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Route", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AgencyId")
                        .HasColumnType("text")
                        .HasColumnName("agency_id");

                    b.Property<int?>("ContinuousDropOff")
                        .HasColumnType("integer")
                        .HasColumnName("continuous_drop_off");

                    b.Property<int?>("ContinuousPickup")
                        .HasColumnType("integer")
                        .HasColumnName("continuous_pickup");

                    b.Property<string>("RouteColor")
                        .HasColumnType("text")
                        .HasColumnName("route_color");

                    b.Property<string>("RouteDesc")
                        .HasColumnType("text")
                        .HasColumnName("route_desc");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteLongName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_long_name");

                    b.Property<string>("RouteShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_short_name");

                    b.Property<int?>("RouteSortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("route_sort_order");

                    b.Property<string>("RouteTextColor")
                        .HasColumnType("text")
                        .HasColumnName("route_text_color");

                    b.Property<int>("RouteType")
                        .HasColumnType("integer")
                        .HasColumnName("route_type");

                    b.Property<string>("RouteUrl")
                        .HasColumnType("text")
                        .HasColumnName("route_url");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_routes");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_gtfs_routes_route_id");

                    b.ToTable("gtfs_routes", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Shape", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Point>("Geom")
                        .HasColumnType("geometry (point)")
                        .HasColumnName("geom")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<double?>("ShapeDistTraveled")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_dist_traveled");

                    b.Property<string>("ShapeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shape_id");

                    b.Property<double>("ShapePtLat")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_pt_lat");

                    b.Property<double>("ShapePtLon")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_pt_lon");

                    b.Property<int>("ShapePtSequence")
                        .HasColumnType("integer")
                        .HasColumnName("shape_pt_sequence");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_shapes");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_gtfs_shapes_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("ShapeId")
                        .HasDatabaseName("ix_gtfs_shapes_shape_id");

                    b.ToTable("gtfs_shapes", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Stop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point)")
                        .HasColumnName("location")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("location_type");

                    b.Property<string>("ParentStation")
                        .HasColumnType("text")
                        .HasColumnName("parent_station");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("text")
                        .HasColumnName("platform_code");

                    b.Property<string>("StopCode")
                        .HasColumnType("text")
                        .HasColumnName("stop_code");

                    b.Property<string>("StopDesc")
                        .HasColumnType("text")
                        .HasColumnName("stop_desc");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<double>("StopLat")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_lat");

                    b.Property<double>("StopLon")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_lon");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_name");

                    b.Property<string>("StopTimezone")
                        .HasColumnType("text")
                        .HasColumnName("stop_timezone");

                    b.Property<string>("StopUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_url");

                    b.Property<int?>("WheelchairBoarding")
                        .HasColumnType("integer")
                        .HasColumnName("wheelchair_boarding");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_stops");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_gtfs_stops_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("StopId")
                        .HasDatabaseName("ix_gtfs_stops_stop_id");

                    b.ToTable("gtfs_stops", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.StopArea", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StopAreaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_area_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_stop_areas");

                    b.HasIndex("StopAreaId")
                        .HasDatabaseName("ix_gtfs_stop_areas_stop_area_id");

                    b.ToTable("gtfs_stop_areas", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.StopTime", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrival_time");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departure_time");

                    b.Property<int?>("DropOffType")
                        .HasColumnType("integer")
                        .HasColumnName("drop_off_type");

                    b.Property<int?>("PickupType")
                        .HasColumnType("integer")
                        .HasColumnName("pickup_type");

                    b.Property<double?>("ShapeDistTraveled")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_dist_traveled");

                    b.Property<string>("StopHeadsign")
                        .HasColumnType("text")
                        .HasColumnName("stop_headsign");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("stop_sequence");

                    b.Property<int?>("Timepoint")
                        .HasColumnType("integer")
                        .HasColumnName("timepoint");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_stop_times");

                    b.HasIndex("StopId")
                        .HasDatabaseName("ix_gtfs_stop_times_stop_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_gtfs_stop_times_trip_id");

                    b.ToTable("gtfs_stop_times", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Transfer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("FromStopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_stop_id");

                    b.Property<int?>("MinTransferTime")
                        .HasColumnType("integer")
                        .HasColumnName("min_transfer_time");

                    b.Property<string>("ToStopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_stop_id");

                    b.Property<int>("TransferType")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_type");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_transfers");

                    b.HasIndex("FromStopId")
                        .HasDatabaseName("ix_gtfs_transfers_from_stop_id");

                    b.HasIndex("ToStopId")
                        .HasDatabaseName("ix_gtfs_transfers_to_stop_id");

                    b.ToTable("gtfs_transfers", (string)null);
                });

            modelBuilder.Entity("Tranzor.Models.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("BikesAllowed")
                        .HasColumnType("integer")
                        .HasColumnName("bikes_allowed");

                    b.Property<string>("BlockId")
                        .HasColumnType("text")
                        .HasColumnName("block_id");

                    b.Property<int?>("DirectionId")
                        .HasColumnType("integer")
                        .HasColumnName("direction_id");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("ShapeId")
                        .HasColumnType("text")
                        .HasColumnName("shape_id");

                    b.Property<string>("TripHeadsign")
                        .HasColumnType("text")
                        .HasColumnName("trip_headsign");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<string>("TripShortName")
                        .HasColumnType("text")
                        .HasColumnName("trip_short_name");

                    b.Property<int?>("WheelchairAccessible")
                        .HasColumnType("integer")
                        .HasColumnName("wheelchair_accessible");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_trips");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_gtfs_trips_route_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_gtfs_trips_service_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_gtfs_trips_trip_id");

                    b.ToTable("gtfs_trips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
